### ISSUE TITLE
Auto-sizing of Width and Height is not working when size other than btn-md is used

### ISSUE THREAD

**Issue by sstragier** [ziscloud/angular-bootstrap-toggle#25] opened 2017-12-20 22:07 UTC
When using size with the toggle, the width and height that are auto calculated are for btn-md. It seems like the issue is because the computeStyle function is being called before the size attributes are applied to the DOM.

Here is sample code to reproduce:
```
<toggle ng-model="model" size="btn-xs"></toggle>
<button class="btn btn-xs btn-primary">Size of .btn-xs</button>
```

And here is a plunker showing the issue
https://plnkr.co/edit/ps1b0St62YSLK9e7Mu8n

**Comment by bertysentry** [comment] 2018-03-12 22:29
Hi,

I have the very same issue... :-(

**Comment by mbacelo** [comment] 2018-06-08 14:31
Apparently it works on previous versions (I tried in 0.1.2). Something has changed in the last version that broke sizing options

**Comment by bertysentry** [comment] 2018-10-15 21:21
The issue is fixed in version 0.4.0. Please close the issue to confirm the fix. Thanks!

**Closed** 2018-11-19 12:29 UTC
